---
title: "R Translations Status Dashbaord"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    self_contained: false
    favicon: favicon_32x32.png
    includes:
      in_header: "fragments/ganalytics.html"
      after_body: "fragments/afterInit.html"
    css: ["fragments/custom.css", "css/custom.css"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rvest)
library(stringr)
library(dplyr)
library(htmltools)
library(echarts4r)
library(reactable)
source("global_translations.R")
```

Sidebar {.sidebar data-width=200}
=====================================

```{r, echo=FALSE, results='asis'}
htmltools::includeHTML('fragments/sidebar.html')
```

Home
=====================================

Row {data-height=50}
-------------------------------------



Row
-------------------------------------

### Total Packages Translated

```{r}

```

### 

```{r}

```

### 

```{r}

```

Row
-------------------------------------

### 

```{r}

```

### 

```{r}

```

### 

```{r}

```

Row
-------------------------------------

### 

```{r}

```

### 

```{r}

```

### 

```{r}
")
```


Row {data-height=30}
-------------------------------------

### 


Row
-------------------------------------

### 

```{r}

```

###

```{r}

```

### 

```{r}

```

Row
-------------------------------------

### 

```{r}

```

### 

```{r}

```

<!-- ### Total Hosts -->

<!-- ```{r} -->
<!-- valueBox(host_count, icon = "fa-signal", color = "white") -->
<!-- ``` -->

### 

```{r}

```


Row {data-height=450}
-----------------------------------------------------------------------

### 

```{r}

```

### 

```{r}

```


Row {data-height=400}
-----------------------------------------------------------------------

### 

```{r}

```

Row {data-height=400}
-----------------------------------------------------------------------

### 

```{r}

```



Row {data-height=400}
-----------------------------------------------------------------------

###

```{r}

```

Row {data-height=400}
-----------------------------------------------------------------------

### New 

```{r}

```

Row {data-height=400}
-----------------------------------------------------------------------

### Net 

```{r}

```


Row {data-height=400}
-----------------------------------------------------------------------

### Net 

```{r}

```



```{js}
```